remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
plugins:
  - jekyll-remote-theme

# Site metadata - please add or merge your existing settings below
# If you already have a _config.yml, merge these lines instead of replacing.
title: "Sandra Bohmann"
email: "Sandra.Bohmann@lmu.de"
description: "Academic Website"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Sandra-Bohmann.github.io"

navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Blog"
    url: "/blog/"   # change to where posts are shown in this theme

paginate: 5  # amount of posts to show per page
paginate_path: /page:num/